"""Shared atol/rtol output comparison.

Single source of truth used by:
  - the eval-package verify script generated by package_builder._gen_verify_script
    (runs in the worker subprocess after a tarball ship-and-extract)
  - the batch-time pre-flight verify.py Tier 2 check
    (runs locally against ref/kernel files before any /autoresearch is launched)

Both call sites converged here so an `equal_nan` / dtype / diagnostic-format
divergence between "what verify.py thinks is correct" and "what autoresearch's
real eval thinks is correct" can no longer creep in. autoresearch's eval is
authoritative; this module replicates exactly what it does.

The function is dependency-light (only torch) so it can be bundled into the
worker tarball without dragging the rest of `.autoresearch/scripts/` along.
"""
from __future__ import annotations

from typing import Any


def compare_outputs(out_ref: list, out_new: list,
                    atol: float, rtol: float) -> dict:
    """torch.allclose comparison with autoresearch's exact semantics.

    Behavior (must match the eval-package verify script byte-for-byte):
      - Non-tensor outputs are silently skipped (autoresearch's eval never
        materializes scalar-only outputs through this path; mismatching only
        on the tensor outputs is the contract).
      - Tensors are detached, moved to CPU, cast to float32 (`.float()`).
        Half-precision kernels still get compared at fp32 to match the
        cached reference's dtype.
      - Shape mismatch fails fast with a shape-only diagnostic.
      - Value comparison is `torch.allclose(..., atol=atol, rtol=rtol)`,
        WITHOUT `equal_nan=True`. NaN positions in either side are treated
        as a real mismatch — same as autoresearch.

    Returns:
      {"correctness": bool,
       "diagnostics": list[str],     # one per tensor output
       "max_abs_diff": float | None, # max over all tensor outputs (None if no
                                       tensor pairs were compared)
       "atol": float, "rtol": float}
    """
    import torch  # local import: keeps this module importable without torch

    diagnostics: list[str] = []
    all_close = True
    max_abs_overall: float | None = None

    if len(out_ref) != len(out_new):
        return {
            "correctness": False,
            "diagnostics": [
                f"output count: ref={len(out_ref)} new={len(out_new)}"
            ],
            "max_abs_diff": None,
            "atol": atol, "rtol": rtol,
        }

    for i, (r, n) in enumerate(zip(out_ref, out_new)):
        # Mirror autoresearch's verify script: only tensor pairs participate.
        if not (isinstance(r, torch.Tensor) and isinstance(n, torch.Tensor)):
            continue

        rf = r.detach().cpu().float()
        nf = n.detach().cpu().float()

        if rf.shape != nf.shape:
            all_close = False
            diagnostics.append(
                f"out{i} shape {tuple(rf.shape)} != kernel {tuple(nf.shape)}"
            )
            continue

        abs_diff = (rf - nf).abs()
        max_abs = float(abs_diff.max().item())
        if max_abs_overall is None or max_abs > max_abs_overall:
            max_abs_overall = max_abs

        if not torch.allclose(rf, nf, atol=atol, rtol=rtol):
            all_close = False
            rel_denom = rf.abs().clamp_min(1e-12)
            max_rel = float((abs_diff / rel_denom).max().item())
            n_bad = int((abs_diff > (atol + rtol * rf.abs())).sum().item())
            n_tot = int(rf.numel())
            diagnostics.append(
                f"out{i}: max_abs={max_abs:.3e} max_rel={max_rel:.3e} "
                f"bad_elems={n_bad}/{n_tot} ({100.0 * n_bad / n_tot:.2f}%)"
            )
        else:
            diagnostics.append(f"out{i}: OK (max_abs={max_abs:.3e})")

    return {
        "correctness": all_close,
        "diagnostics": diagnostics,
        "max_abs_diff": max_abs_overall,
        "atol": atol, "rtol": rtol,
    }
